apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: huoneisto-utils
spec:
  template:
    metadata:
      labels:
        run: huoneisto-utils
    spec:
      containers:
      - name: huoneisto-utils
        image:  gcr.io/jntlserv0/huoneisto_utils:0.6
        env:
        - name: THEMES
          value: realestate
        - name: LOCALE
          value: fi_FI
        - name: DBADMIN
          value: admin
        - name: ADDRS
          value: mymongo-controller
        - name: SITES
          value: huoneisto.mobi               
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
 
