apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: huoneisto-utils
  namespace: huoneisto
spec:
  template:
    metadata:
      labels:
        run: huoneisto-utils
    spec:
      containers:
      - name: huoneisto-utils
        image: remotejob/huoneisto_utils:1.7cron
        env:
        - name: THEMES
          value: realestate
        - name: LOCALE
          value: fi_FI
        - name: DBADMIN
          value: admin
        - name: ADDRS
          value: mydocker-service
        - name: SITES
          value: huoneisto.mobi               
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        - name: TICK
          value: "120"     
 
